---

name: windows

on: [push]

jobs:
  test:
    runs-on: windows-2019

    strategy:
      matrix:
        version: ["2.4.x", "2.5.x", "2.6.x"]

    steps:
      - uses: actions/checkout@master

      - name: Setup released rubies
        uses: actions/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.version }}

      - name: Run CI checks
        run: |
          bin/setup.sh
          bin/rake compile test
        shell: bash
