---

name: windows

on: [push]

jobs:
  test:
    runs-on: windows-2019

    strategy:
      matrix:
        version: ["2.4.9-1", "2.5.7-1", "2.6.5-1", "head"]

    steps:
      - uses: actions/checkout@master

      - name: Download ruby installer
        run: |
          $(new-object net.webclient).DownloadFile("https://github.com/oneclick/rubyinstaller2/releases/download/rubyinstaller-${{ matrix.version }}/rubyinstaller-${{ matrix.version }}-x64.exe", "$pwd/ruby-setup.exe")
          cmd /c ruby-setup.exe /verysilent /dir=C:/Ruby${{ matrix.version }}-x64
        if: matrix.version != 'head'

      - name: Download ruby-head installer
        run: |
          $(new-object net.webclient).DownloadFile("https://github.com/oneclick/rubyinstaller2/releases/download/rubyinstaller-${{ matrix.version }}/rubyinstaller-${{ matrix.version }}-x64.exe", "$pwd/ruby-setup.exe")
          cmd /c ruby-setup.exe /verysilent /dir=C:/Ruby${{ matrix.version }}-x64
        if: matrix.version == 'head'

      - name: Put installed ruby in path
        run: set PATH=C:\Ruby${{ matrix.version }}-x64\bin;C:\Program Files\Git\cmd;C:/Windows/system32;C:\Program Files\Git\usr\bin
        shell: cmd

      - name: Run CI checks
        run: |
          bin/setup.sh
          bin/rake compile test
        shell: bash
